"""RAG (Retrieval-Augmented Generation) pipeline implementation."""
import os
from typing import List, Dict, Any, Optional

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import OpenAIEmbeddings
from langchain_community.vectorstores import Chroma
from chromadb.config import Settings as ChromaSettings
import json
from core.config import settings

class DocumentLoader:
    """Handles document loading and chunking."""

    def __init__(self):
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=1000,
            chunk_overlap=200,
            separators=["\n\n", "\n", " ", ""]
        )

    def load_pdf(self, file_path: str) -> List[str]:
        """Load and chunk a PDF document."""
        loader = PyPDFLoader(file_path)
        documents = loader.load()
        chunks = self.text_splitter.split_documents(documents)
        return [chunk.page_content for chunk in chunks]

    def load_text(self, file_path: str) -> List[str]:
        """Load and chunk a text document."""
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        chunks = self.text_splitter.split_text(content)
        return chunks

    def load_document(self, file_path: str, file_type: str) -> List[str]:
        """Load a document based on its type."""
        if file_type == 'pdf':
            return self.load_pdf(file_path)
        elif file_type in ['txt', 'md', 'docx']:
            return self.load_text(file_path)
        else:
            raise ValueError(f"Unsupported file type: {file_type}")


class VectorStore:
    """Manages vector store operations."""

    def __init__(self):
        self.embeddings = OpenAIEmbeddings(
            model=settings.EMBEDDING_MODEL,
            openai_api_key=settings.OPENAI_API_KEY
        )

        # Initialize Chroma through LangChain community interface
        self.store = Chroma(
            persist_directory=settings.CHROMA_PATH,
            embedding_function=self.embeddings,
            client_settings=ChromaSettings(
                anonymized_telemetry=False,
                allow_reset=True,
            ),
        )

    def add_documents(self, document_id: int, chunks: List[str], metadata: Dict[str, Any]):
        """Add document chunks to vector store."""

        # Prepare data for insertion
        ids = [f"doc_{document_id}_chunk_{i}" for i in range(len(chunks))]
        metadatas = [
            {
                "document_id": str(document_id),
                "chunk_index": str(i),
                **metadata
            }
            for i in range(len(chunks))
        ]

        # Add to collection with embeddings auto-generated by Chroma
        self.store.add_texts(
            texts=chunks,
            metadatas=metadatas,
            ids=ids
        )

    def search(self, query: str, top_k: int = 5, document_filter: Optional[List[int]] = None) -> List[Dict[str, Any]]:
        """Search for relevant documents."""

        # Prepare freshrich filter if document filter is provided
        where = None
        if document_filter:
            where = {
                "document_id": {
                    "$in": [str(doc_id) for doc_id in document_filter]
                }
            }

        # Similarity search with score
        results_with_scores = self.store.similarity_search_with_score(
            query,
            k=top_k,
            filter=where
        )

        # Format results
        formatted_results = []
        for doc, score in results_with_scores:
            formatted_results.append({
                "content": doc.page_content,
                "metadata": doc.metadata,
                "distance": score,
                "relevance_score": 1 - score if score is not None else None
            })

        return formatted_results

    def delete_document(self, document_id: int):
        """Delete all chunks of a document."""
        self.store.delete(filter={"document_id": str(document_id)})

    def update_document(self, document_id: int, chunks: List[str], metadata: Dict[str, Any]):
        """Update a document by deleting and re-adding."""
        self.delete_document(document_id)
        self.add_documents(document_id, chunks, metadata)


class RAGPipeline:
    """Main RAG pipeline orchestrator."""

    def __init__(self):
        self.document_loader = DocumentLoader()
        self.vector_store = VectorStore()

    def ingest_document(self, file_path: str, file_type: str, document_id: int, metadata: Dict[str, Any]):
        """Ingest a document into the RAG pipeline."""
        # Load and chunk the document
        chunks = self.document_loader.load_document(file_path, file_type)
        
        # Add to vector store
        self.vector_store.add_documents(document_id, chunks, metadata)
        
        return {
            "document_id": document_id,
            "chunks_count": len(chunks),
            "status": "success"
        }

    def retrieve_context(self, query: str, top_k: int = 5, document_filter: Optional[List[int]] = None) -> List[Dict[str, Any]]:
        """Retrieve relevant context for a query."""
        return self.vector_store.search(query, top_k, document_filter)

    def delete_document(self, document_id: int):
        """Delete a document from the RAG pipeline."""
        self.vector_store.delete_document(document_id)
